### ISSUE TITLE
Show two pivotUI tables on same page, one with hidden totals

### ISSUE THREAD

**Issue by tsando** [nicolaskruchten/pivottable#658]
Does anyone have a recipe on how to have 2 pivot tables showing on the same page, but one of them with hidden totals? Hence the solution to alter the css as suggested here https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#totals  isn't applicable (or at least I couldn't get it to work for me). The only thing that worked was this:

```
$("#output-hidden").pivotUI({
.
.
onRefresh: function(config) {
//$("#output-hidden").find('select').addClass('hidden');
$("#output-hidden").find('.rowTotal').addClass('hidden');
$("#output-hidden").find('.colTotal').addClass('hidden');
$("#output-hidden").find('.pvtGrandTotal').addClass('hidden');
$("#output-hidden").find('.pvtTotalLabel').addClass('hidden');
},
.
.
});
```

Thank you.

**Comment by nicolaskruchten** [comment]
The solution above works right? If so, then something like the following is an equivalent pure-CSS variant on the recommendation in the FAQ.

```css
#output-hidden select, #output-hidden .rowTotal, #output-hidden .colTotal, #output-hidden .pvtGrandTotal, #output-hidden .pvtTotalLabel {display: none}
```
